default:
    @just --list

build:
    @docker compose build

up: build
    @docker compose up -d

logs:
    @docker compose logs -f

prod:
    @docker compose -f docker-compose-prod.yml build
    @docker compose -f docker-compose-prod.yml up -d

down:
    @docker compose down
